// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.0 (Build Build 614 04/24/2018)
// Created on Sun Dec 08 00:19:52 2019

if_id if_id_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.rst(rst_sig) ,	// input  rst_sig
	.stall(stall_sig) ,	// input [5:0] stall_sig
	.if_pc(if_pc_sig) ,	// input [15:0] if_pc_sig
	.if_inst(if_inst_sig) ,	// inout [15:0] if_inst_sig
	.rom_addr_o(rom_addr_o_sig) ,	// output [15:0] rom_addr_o_sig
	.id_pc(id_pc_sig) ,	// output [15:0] id_pc_sig
	.id_inst(id_inst_sig) ,	// output [15:0] id_inst_sig
	.wr_Mem(wr_Mem_sig) ,	// input [1:0] wr_Mem_sig
	.mem_addr_i(mem_addr_i_sig) ,	// input [15:0] mem_addr_i_sig
	.mem_data_i(mem_data_i_sig) ,	// input [15:0] mem_data_i_sig
	.mem_data_o(mem_data_o_sig) ,	// output [15:0] mem_data_o_sig
	.we(we_sig) 	// input  we_sig
);

